plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.g2.moviebooking'
    compileSdk 35

    defaultConfig {
        applicationId "com.g2.moviebooking"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

// Add this at the top of the dependencies block
def localProperties = new Properties()
localProperties.load(new FileInputStream(rootProject.file("local.properties")))
def zaloPayLibDir = localProperties.getProperty('zalopay.lib.dir', '')

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout

    // Zalo Pay
    implementation fileTree(
            dir: zaloPayLibDir,
            include: ['*.aar', '*.jar'],
            exclude: [''])
    implementation("com.squareup.okhttp3:okhttp:4.6.0")
    implementation("commons-codec:commons-codec:1.14")

    // Thư viện test
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // Firebase BOM để quản lý phiên bản Firebase
    implementation platform('com.google.firebase:firebase-bom:33.10.0')

    // Firebase Auth và Firestore
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'

    // Retrofit để gọi API và chuyển đổi JSON
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // Google Play Services để đăng nhập bằng Google
    implementation 'com.google.android.gms:play-services-auth:21.3.0'

    // Glide để tải và hiển thị hình ảnh
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'

    // ViewPager2 để tạo giao diện phân trang
    implementation 'androidx.viewpager2:viewpager2:1.0.0'

    // ZXing for QR code generation
    implementation 'com.google.zxing:core:3.4.1'

    // CardView để tạo giao diện thẻ
    implementation 'androidx.cardview:cardview:1.0.0'
}